### PR TITLE
API: Implement proposed changes

### LINKED ISSUE #28: API changes
## Issues with the current API

1. In a normal scenario, app authors have to try / catch the `activate()` and store the error in the state so that users can be presented a connection error message. This is verbose and takes us farther from the goal of keeping the boilerplate code as minimal as possible `useWallet()`.
2. Passing both the connector identifier and the state, using `activating`, `activated` and `connected`, requires consumers of the library to test several variables to know the current state and the connector identifier.
3. Using a mix of the term “activated” and the term “connected” is confusing. “activated” is coming from [EIP 1102](https://eips.ethereum.org/EIPS/eip-1102), which both defines and deprecates it. Most Ethereum providers use the term “connect” for this (see image below).

<p align=center>

## Proposed changes

The goal of these changes is generally to:

- Make it possible to use the library by only importing the default export, `useWallet()`.
- Remove the confusion between “connected” and “activated” by only using the term “connect”.
- Keep the boilerplate to a minimum for simple cases.

### `connect()` and `disconnect()`

`connect(id)` and `disconnect()` would replace `activate(id)` and `deactivate()`. This is to remove any reference to the term “activation” and increase consistency.

```jsx
function App() {
  const { account, connect, disconnect } = useWallet()
  return (
    <button onClick={account ? disconnect : connect}>
      {account ? 'Connect' : 'Disconnect'}
    </button>
  )
}
```

### `status`

`status` would be a new exported value that would contain the current status of the wallet connection. It would have take one of these values at any given time:

- `"disconnected"`: no wallet connected (default state).
- `"connecting"`: trying to connect to the wallet.
- `"connected"`: connected to the wallet (i.e. the account is available).
- `"error"`: a connection error happened.

These are strings and not symbols so that users don’t have to import many symbols.

These values would get deprecated: `activated`, `activating` and `connected`.

Having a status `connected` guarantees that `account` is not `null`.

```jsx
function App() {
  const { account, connect, status } = useWallet()

  if (status === 'connecting') {
    return <p>Connecting…</p>
  }

  if (status === 'connected') {
    return <p>Connected as {account}</p>
  }

  // status === 'disconnected' or status === 'error'
  return <button onClick={() => connect('injected')}>Connect</button>
}
```

### `error` and `reset()`

`error` is a new value that contains the error object that comes with an `"error"` status.

There are different types of errors exported by module:

- `UnsupportedChainError`
- `UnsupportedConnectorError`
- `RejectedActivationError`
- `ConnectorConfigError`

`error` would be `null` when the status is not `error`, otherwise it would get populated by the corresponding error instance.

Users would have the possibility to import the error constructors and use `instanceof`, or to use the `name` property.

The `message` property can also be used to display the current error.

Calling `reset()` will make `status` go back to `disconnected`, and `error` back to `null`. Calling `connect()` would also clear the error state before initiating the new connection.

```jsx
function App() {
  const { account, connect, error, reset, status } = useWallet()

  if (status === 'connecting') {
    return <p>Connecting…</p>
  }

  if (status === 'connected') {
    return <p>Connected as {account}</p>
  }

  if (status === 'error') {
    return (
      <div>
        <p>Error: {error.message}.</p>
        <button onClick={() => reset()}>OK</button>
      </div>
    )
  }

  // status === 'disconnected'
  return <button onClick={() => connect('injected')}>Connect</button>
}
```

@Evalir @sohkai Let me know what you guys think!

### PR DESCRIPTION
**Pull request by Evalir**
Closes #28.

**Feedback is extremely appreciated!** Implements the changes proposed in the linked issue. Apart from this, a new property is added: `connector`. This will keep track of the _wallet_ that is trying to be / is activated (metamask, frame, squarelink, etc) as this was not in the scope of the spec proposed.

A few tentative / pending things apart from a thorough review to catch anything else we might wanna deprecate:
- [ ] (Discuss) Implemented auto-connection to the latest wallet selected?
- [ ] Update docs

_Note: The amount of lines changed seems daunting, but 99% of that is just .lock files 🙄 the actual changes are very quick to review!_

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -252,56 +259,65 @@ function UseWalletProvider({
         })
 
       if (!web3ReactConnector) {
-        throw new UnsupportedConnectorError(connectorId)
+        setStatus('error')
+        setError(UnsupportedConnectorError(connectorId))
```
Comment (andy-hook) [inline src/index.js:263]: Should we be invoking these via `new`?

File: src/index.js [hunk 2]
```diff
@@ -217,28 +217,35 @@ function UseWalletProvider({
...
 
-      deactivate()
+      reset()
 
       // Check if another connection has happened right after deactivate().
       if (id !== activationId.current) {
         return
       }
 
+      // If no connection happene, we're in the right context, and we can safely update
```
Comment (andy-hook) [inline src/index.js:241]:
```suggestion
      // If no connection happens, we're in the right context and can safely update
```
Do you think this reads better?

File: src/index.js [hunk 3]
```diff
@@ -217,28 +217,35 @@ function UseWalletProvider({
...
+      // the connection stage status
+      setStatus('connecting')
+
       if (!connectors[connectorId]) {
-        throw new UnsupportedConnectorError(connectorId)
+        setStatus('error')
+        setError(UnsupportedConnectorError(connectorId))
```
Comment (andy-hook) [inline src/index.js:247]: Should we update the naming of these errors per [this suggestion](https://github.com/aragon/use-wallet/issues/28#issuecomment-600036707)?

File: src/index.js (hunk 1 above)
Comment (Evalir) [reply src/index.js:263]: Yup, true 👍

File: src/index.js (hunk 2 above)
Comment (Evalir) [reply src/index.js:241]: Definitely!

File: src/index.js (hunk 3 above)
Comment (Evalir) [reply src/index.js:247]: I think it's a good renaming, that way we don't have a prefix + suffix, just the later. What do you think @bpierre ?

File: examples/simple-connect/index.js [hunk 4]
```diff
@@ -18,16 +14,11 @@ function App() {
...
-    } catch (err) {
-      if (err instanceof RejectedActivationError) {
-        setLastError('Connection error: the user rejected the activation')
-      }
-      setLastError(err.message)
-    }
+    await wallet.connect(connector)
   }
 
+  useEffect(() => setLastError(wallet.error?.name ?? ''), [wallet])
```
Comment (andy-hook) [inline examples/simple-connect/index.js:20]: Just curious, should we continue to reference `message` in the examples? it feels like it might be a more useful descriptor.

**Comment by andy-hook** [comment]
This looks pretty solid to me! @bpierre did you want to have a quick look?

File: src/index.js [hunk 5]
```diff
@@ -217,28 +217,35 @@ function UseWalletProvider({
...
 
       // Check if another connection has happened right after deactivate().
       if (id !== activationId.current) {
         return
       }
 
+      // If no connection happens, we're in the right context and can safely update
+      // the connection stage status
+      setStatus('connecting')
+
```
Comment (bpierre) [inline src/index.js:244]: Nitpicking: should we move this after the `if (!connectors[connectorId])`, so we don’t call `setStatus()` twice?

File: src/index.js [hunk 6]
```diff
@@ -252,56 +259,65 @@ function UseWalletProvider({
...
+          setError(new UnsupportedChainError(-1, chainId))
+          return
         }
         // It might have thrown with an error known by the connector
         if (connector.handleActivationError) {
-          connector.handleActivationError(err)
+          const thrownError = connector.handleActivationError(err)
+          setError(thrownError)
+          return
         }
```
Comment (bpierre) [inline src/index.js:293]: We should test if the error is actually handled by the connector here. Otherwise, having a connector with a `handleActivationError` method that doesn’t handle the error would return, and call `setError()` with `undefined` instead of `err`.

We could do this instead:

```jsx
const handledError = connector.handleActivationError?.(err)
if (handledError) {
  setError(handledError)
  return
}
```

Also changed `thrownError` to `handledError`, as it doesn’t get thrown anymore.

File: src/index.js [hunk 7]
```diff
@@ -252,56 +259,65 @@ function UseWalletProvider({
...
     }
 
     let cancel = false
 
-    setConnected(true)
     setIsContract(false)
 
     getAccountIsContract(ethereum, account).then(isContract => {
       if (!cancel) {
+        setStatus('connected')
```
Comment (bpierre) [inline src/index.js:314]: Did this moved here in order to get `status === 'connected'` at the same time than we get the proper `isContract`?

IIRC the idea was to connect as fast as possible, and update other things asynchronously (`balance` and `isContract`). But I agree that not knowing when the `isContract` information is available is a problem. What about having `isContract === null` by default, then setting it to `true` or `false` asynchronously?

File: src/index.js [hunk 8]
```diff
@@ -252,56 +259,65 @@ function UseWalletProvider({
...
+        setError(err)
       }
     },
-    [chainId, connectors, deactivate, web3ReactContext]
+    [chainId, connectors, reset, web3ReactContext]
   )
 
   useEffect(() => {
     if (!account || !ethereum) {
+      setStatus('disconnected')
```
Comment (bpierre) [inline src/index.js:304]: Wondering if there was a reason to move this here rather than leaving it [in the `useEffect()` callback](https://github.com/aragon/use-wallet/pull/42/files#diff-1fdf421c05c1140f6d71444ea2b27638L304)? :thinking:

File: src/index.js (hunk 3 above)
Comment (bpierre) [reply src/index.js]: Oh sorry I missed this comment, yes I think these are better names! :+1:

File: examples/simple-connect/index.js (hunk 4 above)
Comment (bpierre) [reply examples/simple-connect/index.js:20]: Also wondering if we should keep one of the example with custom error messages, to demonstrate how to check for a specific error type using `typeof`?

File: .gitignore [hunk 9]
```diff
@@ -1,4 +1,5 @@
 node_modules/
 .cache/
+.next/
```
[the remark this answers is not in the document]
Comment (Evalir) [reply .gitignore:3]: Let's move it into a `.gitignore` for the next example; it's the only one that should need it.

File: examples/nextjs/pages/index.js [hunk 10]
```diff
@@ -14,16 +10,11 @@ function App() {
...
-    } catch (err) {
-      if (err instanceof RejectedActivationError) {
-        setLastError('Connection error: the user rejected the activation')
-      }
-      setLastError(err.message)
-    }
+    await wallet.connect(connector)
   }
 
+  useEffect(() => setLastError(wallet.error?.name ?? ''), [wallet])
```
[the remark this answers is not in the document]
Comment (Evalir) [reply examples/nextjs/pages/index.js:16]: Yeah, definitely not needed anymore!

File: src/index.js (hunk 5 above)
Comment (Evalir) [reply src/index.js:244]: Makes sense!

File: src/index.js (hunk 6 above)
Comment (Evalir) [reply src/index.js:293]: Aah, missed this!

File: src/index.js (hunk 7 above)
Comment (Evalir) [reply src/index.js:316]: Yes, that's why; I was worried about this race condition ocurring for someone that may rely on this for their app. I definitely agree about the suggestion, but my worry is that people may not realize they may have a bug by doing something like:

```
// lots of code
if (!isContract) {
  // handle this case
}
```

When the account is _actually_ a contract account. What about having `isContract === null`, and having strings define if is a contract or not, like `'contract'` or `'normal'`? The naming's definitely not precise enough, but just an idea. :)

File: src/index.js (hunk 8 above)
Comment (Evalir) [reply src/index.js:306]: Ah shoot; got confused here and thought there was a possible race condition we could have this case but not be `disconnected` in status. 😅

**Comment by Evalir** [comment]
@bpierre @andy-hook We can have another round now!

File: src/connectors.js [hunk 11]
```diff
@@ -143,7 +143,7 @@ export function getConnectors(chainId, connectorsInitsOrConfigs = {}) {
       },
       handleActivationError(err) {
         if (err instanceof WalletConnectUserRejectedRequestError) {
-          throw new RejectedActivationError()
+          return new ConnectionRejectedError()
```
Comment (sohkai) [inline src/connectors.js:146]: Just wanted to sanity check here... are these supposed to be `return`s?

Comment (Evalir) [reply src/connectors.js:146]: Yes; we don't want to throw the error again, as we're in a `catch` statement already. What we wanna do is get the error, and set it to state it's available on the `error` prop.

File: src/index.js (hunk 7 above)
Comment (bpierre) [reply src/index.js:315]: Yes that sounds good! Should we have a name more like `type` or `accountType` then?

File: examples/nextjs/pages/index.js [hunk 12]
```diff
@@ -1,30 +1,23 @@
...
   const blockNumber = wallet.getBlockNumber()
 
-  const activate = async connector => {
-    setLastError('')
-
-    await wallet.connect(connector)
-  }
-
-  useEffect(() => setLastError(wallet.error?.name ?? ''), [wallet])
+  const activate = async connector => await wallet.connect(connector)
```
Comment (bpierre) [inline examples/nextjs/pages/index.js:9]: We could also remove the `async` / `await` since we don’t really need to wait for it to finish:

```suggestion
  const activate = connector => {
    wallet.connect(connector)
  }
```

**Comment by Evalir** [comment]
Sure, let's split it up!

File: src/index.js (hunk 7 above)
Comment (Evalir) [reply src/index.js:315]: Yep! `type` sounds good to me, as I think that the fact that it's coming from `use-wallet` is enough context.
